/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RuknlarRouteImport } from './routes/ruknlar'
import { Route as MaqolalarRouteImport } from './routes/maqolalar'
import { Route as ArxivRouteImport } from './routes/arxiv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudioIndexRouteImport } from './routes/audio.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MaqolaIdRouteImport } from './routes/maqola.$id'
import { Route as AudioIdRouteImport } from './routes/audio.$id'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminMaqolalarRouteImport } from './routes/admin.maqolalar'
import { Route as AdminAudioRouteImport } from './routes/admin.audio'

const RuknlarRoute = RuknlarRouteImport.update({
  id: '/ruknlar',
  path: '/ruknlar',
  getParentRoute: () => rootRouteImport,
} as any)
const MaqolalarRoute = MaqolalarRouteImport.update({
  id: '/maqolalar',
  path: '/maqolalar',
  getParentRoute: () => rootRouteImport,
} as any)
const ArxivRoute = ArxivRouteImport.update({
  id: '/arxiv',
  path: '/arxiv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioIndexRoute = AudioIndexRouteImport.update({
  id: '/audio/',
  path: '/audio/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaqolaIdRoute = MaqolaIdRouteImport.update({
  id: '/maqola/$id',
  path: '/maqola/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioIdRoute = AudioIdRouteImport.update({
  id: '/audio/$id',
  path: '/audio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMaqolalarRoute = AdminMaqolalarRouteImport.update({
  id: '/admin/maqolalar',
  path: '/admin/maqolalar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAudioRoute = AdminAudioRouteImport.update({
  id: '/admin/audio',
  path: '/admin/audio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arxiv': typeof ArxivRoute
  '/maqolalar': typeof MaqolalarRoute
  '/ruknlar': typeof RuknlarRoute
  '/admin/audio': typeof AdminAudioRoute
  '/admin/maqolalar': typeof AdminMaqolalarRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/audio/$id': typeof AudioIdRoute
  '/maqola/$id': typeof MaqolaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/audio/': typeof AudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arxiv': typeof ArxivRoute
  '/maqolalar': typeof MaqolalarRoute
  '/ruknlar': typeof RuknlarRoute
  '/admin/audio': typeof AdminAudioRoute
  '/admin/maqolalar': typeof AdminMaqolalarRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/audio/$id': typeof AudioIdRoute
  '/maqola/$id': typeof MaqolaIdRoute
  '/admin': typeof AdminIndexRoute
  '/audio': typeof AudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arxiv': typeof ArxivRoute
  '/maqolalar': typeof MaqolalarRoute
  '/ruknlar': typeof RuknlarRoute
  '/admin/audio': typeof AdminAudioRoute
  '/admin/maqolalar': typeof AdminMaqolalarRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/audio/$id': typeof AudioIdRoute
  '/maqola/$id': typeof MaqolaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/audio/': typeof AudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arxiv'
    | '/maqolalar'
    | '/ruknlar'
    | '/admin/audio'
    | '/admin/maqolalar'
    | '/admin/subscribers'
    | '/audio/$id'
    | '/maqola/$id'
    | '/admin/'
    | '/audio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arxiv'
    | '/maqolalar'
    | '/ruknlar'
    | '/admin/audio'
    | '/admin/maqolalar'
    | '/admin/subscribers'
    | '/audio/$id'
    | '/maqola/$id'
    | '/admin'
    | '/audio'
  id:
    | '__root__'
    | '/'
    | '/arxiv'
    | '/maqolalar'
    | '/ruknlar'
    | '/admin/audio'
    | '/admin/maqolalar'
    | '/admin/subscribers'
    | '/audio/$id'
    | '/maqola/$id'
    | '/admin/'
    | '/audio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArxivRoute: typeof ArxivRoute
  MaqolalarRoute: typeof MaqolalarRoute
  RuknlarRoute: typeof RuknlarRoute
  AdminAudioRoute: typeof AdminAudioRoute
  AdminMaqolalarRoute: typeof AdminMaqolalarRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AudioIdRoute: typeof AudioIdRoute
  MaqolaIdRoute: typeof MaqolaIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AudioIndexRoute: typeof AudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ruknlar': {
      id: '/ruknlar'
      path: '/ruknlar'
      fullPath: '/ruknlar'
      preLoaderRoute: typeof RuknlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maqolalar': {
      id: '/maqolalar'
      path: '/maqolalar'
      fullPath: '/maqolalar'
      preLoaderRoute: typeof MaqolalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arxiv': {
      id: '/arxiv'
      path: '/arxiv'
      fullPath: '/arxiv'
      preLoaderRoute: typeof ArxivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/': {
      id: '/audio/'
      path: '/audio'
      fullPath: '/audio/'
      preLoaderRoute: typeof AudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maqola/$id': {
      id: '/maqola/$id'
      path: '/maqola/$id'
      fullPath: '/maqola/$id'
      preLoaderRoute: typeof MaqolaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/$id': {
      id: '/audio/$id'
      path: '/audio/$id'
      fullPath: '/audio/$id'
      preLoaderRoute: typeof AudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/maqolalar': {
      id: '/admin/maqolalar'
      path: '/admin/maqolalar'
      fullPath: '/admin/maqolalar'
      preLoaderRoute: typeof AdminMaqolalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audio': {
      id: '/admin/audio'
      path: '/admin/audio'
      fullPath: '/admin/audio'
      preLoaderRoute: typeof AdminAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArxivRoute: ArxivRoute,
  MaqolalarRoute: MaqolalarRoute,
  RuknlarRoute: RuknlarRoute,
  AdminAudioRoute: AdminAudioRoute,
  AdminMaqolalarRoute: AdminMaqolalarRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AudioIdRoute: AudioIdRoute,
  MaqolaIdRoute: MaqolaIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AudioIndexRoute: AudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
